language: bash
dist: bionic
services:
  - docker
env:
  - VERSION=1.5

jobs:
  include:
    - arch: amd64
    - arch: arm64
        
before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
script:
  - docker build . --tag carcaral47/litedashboard:${VERSION}
  - docker push carcaral47/litedashboard:${VERSION}
