jobs:
  include:
    - os: linux
      arch: amd64
      services:
        - docker
      dist: trusty
      env:
        - ARCH=amd64
    - os: linux
      arch: arm64
      services:
        - docker
      dist: trusty
      env:
        - ARCH=arm64
 script: 
  - docker build . --tag litedashboard:1.4-$ARCH
