services:
  - docker

jobs:
  include:
    - os: linux
      arch: amd64
      dist: trusty
      env:
        ARCH=amd64
    - os: linux
      arch: arm64
      dist: trusty
      env:
        ARCH=arm64
      
 script: cd docker build . --tag litedashboard:1.4-$ARCH

