language: bash
dist: focal
services:
  - docker
env:
  - DOCKER_CLI_EXPERIMENTAL=enabled    
before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker buildx create --name builder --platform linux/amd64,linux/arm64,linux/arm
  - docker buildx use builder
  - docker buildx inspect --bootstrap
script:
  - docker buildx build --platform linux/amd64,linux/arm64,linux/arm -t carcaral47/litedashboard:1.5 . --push
