language: bash
dist: bionic
services:
  - docker

jobs:
  include:
    - arch: amd64
      env:
        - ARCH=amd64
    - arch: arm64
      env:
        - ARCH=arm64
        
script:
  - docker build . --tag litedashboard:1.5-$ARCH
