services:
  - docker

jobs:
  include:
    - os: linux
      arch: amd64
      dist: trusty
      script: cd docker build . --tag litedashboard:1.4-amd64
    - os: linux
      arch: arm64
      dist: trusty
      script: cd docker build . --tag litedashboard:1.4-arm

